spring:
  application:
    name: Cards
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swissbank
    username:
      root
    hikari:
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9292